sonar.projectKey=hardhat-website
sonar.projectName=Hardhat Website

sonar.sources=home,utils

sonar.tests=home/tests
sonar.test.inclusions=home/tests/test_*.py

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=**/migrations/**,**/__pycache__/**
sonar.coverage.exclusions=**/migrations/**,home/tests/**